package org.example.carrentalbackend.error;

public enum ExceptionsName {
    USERNAME_ALREADY_EXIST,
    EMAIL_ALREADY_EXIST,
    PHONE_NUMBER_ALREADY_EXIST,
    USER_NOT_FOUND_EXCEPTION,
    VEHICLE_NOT_FOUND_EXCEPTION,
    ORDER_NOT_FOUND_EXCEPTION,
    PAYMENT_NOT_FOUND_EXCEPTION,
    ADDRESS_NOT_FOUND_EXCEPTION,
    INTERNAL_SERVER_ERROR_EXCEPTION,
}
